from .statistics import average
from .statistics import median
from .statistics import deviation
from .interpolate import polynomial
from .interpolate import spline
from .approximate import polynomial
from .integrate import trapezoidal
from .differentiation import differentiate
from .differentiation import monotonicity